name: Angular GitHub CI

on:
  push:
    branches: [ "main", "test" ]
  pull_request:
    branches: [ "main", "test" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./FootballPredictionAngularFrontend/

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version ***REMOVED******REMOVED***
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version ***REMOVED******REMOVED***
        cache: 'npm'
        cache-dependency-path: "./FootballPredictionAngularFrontend/package-lock.json"
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test