name: Build and deploy application to Web App FootballPredictionAPI
on:
  push:
  pull_request:
    branches:
    - main

env:
  AZURE_WEBAPP_NAME: FootballPredictionAPI
  AZURE_WEBAPP_PACKAGE_PATH: FootballPredictionAPI\publish
  AZURE_APIM_RESOURCE_PATH: /
  AZURE_APIM_RESOURCEGROUP: FootballPredictionAPI-rg
  AZURE_APIM_SERVICENAME: FootballPredictionAMS
  AZURE_APIM_API_ID: FootballPredictionAPI
  AZURE_APIM_APPSERVICEURL: https://footballpredictionapi.azurewebsites.net
  SWASHBUCLE_ASPNET_CORE_CLI_PACKAGE_VERSION: 6.4.0
  SWASHBUCKLE_DOTNET_CORE_VERSION: 3.1.x
  API_IMPORT_SPECIFICATION_PATH: FootballPredictionAPI\publish\swagger.json
  API_IMPORT_DLL: FootballPredictionAPI\bin\Release\net7.0\FootballPredictionAPI.dll
  API_IMPORT_VERSION: v1
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 7.0.x
  WORKING_DIRECTORY: FootballPredictionAPI
  TEST_DIRECTORY: FootballPredictionAPITests
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION ***REMOVED******REMOVED***
    - name: Setup SwashBuckle .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.SWASHBUCKLE_DOTNET_CORE_VERSION ***REMOVED******REMOVED***
    - name: Restore
      run: dotnet restore ${{ env.WORKING_DIRECTORY ***REMOVED******REMOVED***
    - name: Build
      run: dotnet build ${{ env.WORKING_DIRECTORY ***REMOVED******REMOVED*** --configuration ${{ env.CONFIGURATION ***REMOVED******REMOVED*** --no-restore
    - name: Test
      run: dotnet test --no-build # ${{ env.TEST_DIRECTORY ***REMOVED******REMOVED*** --no-build
    - name: Publish
      run: dotnet publish ${{ env.WORKING_DIRECTORY ***REMOVED******REMOVED*** --configuration ${{ env.CONFIGURATION ***REMOVED******REMOVED*** --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH ***REMOVED******REMOVED***
    #- name: Install Swashbuckle CLI .NET Global Tool
    #  run: dotnet tool install --global Swashbuckle.AspNetCore.Cli --version ${{ env.SWASHBUCLE_ASPNET_CORE_CLI_PACKAGE_VERSION ***REMOVED******REMOVED***
    #  working-directory: ${{ env.WORKING_DIRECTORY ***REMOVED******REMOVED***
    #- name: Generate Open API Specification Document
    #  run: swagger tofile --output "${{ env.API_IMPORT_SPECIFICATION_PATH ***REMOVED******REMOVED***" "${{ env.API_IMPORT_DLL ***REMOVED******REMOVED***" "${{ env.API_IMPORT_VERSION ***REMOVED******REMOVED***"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH ***REMOVED******REMOVED***
  deploy:
    runs-on: windows-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH ***REMOVED******REMOVED***
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME ***REMOVED******REMOVED***
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH ***REMOVED******REMOVED***
        publish-profile: ${{ secrets.FootballPredictionAPI_91BE ***REMOVED******REMOVED***
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.FootballPredictionAMS_SPN ***REMOVED******REMOVED***
    #- name: Import API into Azure API Management
    #  run: az apim api import --path "${{ env.AZURE_APIM_RESOURCE_PATH ***REMOVED******REMOVED***" --resource-group "${{ env.AZURE_APIM_RESOURCEGROUP ***REMOVED******REMOVED***" --service-name "${{ env.AZURE_APIM_SERVICENAME ***REMOVED******REMOVED***" --api-id "${{ env.AZURE_APIM_API_ID ***REMOVED******REMOVED***" --service-url "${{ env.AZURE_APIM_APPSERVICEURL ***REMOVED******REMOVED***" --specification-path "${{ env.API_IMPORT_SPECIFICATION_PATH ***REMOVED******REMOVED***" --specification-format OpenApi --subscription-required false
    - name: logout
      run: >
        az logout
